server:
  port: 8081
spring:
  application:
    name: library-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2dll:
          create_namespaces: true
  datasource:
    url: jdbc:postgresql://localhost:5444/library
    username: yasha
    password: password
  cloud:
    config:
      uri: http:/localhost:8888
  kafka:
    bootstrap-servers: localhost:9092
    topic: library

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html