server:
  port: 8083


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: library-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/books/**
        - id: diary-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/diary/**





