server:
  port: 8082
spring:
  application:
    name: diary-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5444/library
    username: yasha
    password: password
  cloud:
    config:
      uri: http:/localhost:8888
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

test:
  say: "${my.testmassege}"